### PR TITLE
Fix DeprecationWarning about collections.abc

### LINKED ISSUE #51: Fix DeprecationWarnings
e.g.,
```
zope/testbrowser/_compat.py:44: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping  # noqa
```

### PR DESCRIPTION
**Pull request by jamadden**
Fixes #51

### CODE REVIEW

**Comment by jamadden** [comment]
Because of [github's issues,](https://blog.github.com/2018-10-21-october21-incident-report/), we don't have CI runs of this yet. Hopefully they will get unpaused soon because I'd prefer to wait for successful CI before merging.

**Comment by jamadden** [comment]
Thanks! CI went green. Could we get a PyPI release, please? (Or access for `jamadden`.)

**Comment by mgedmin** [comment]
You have the PyPI bit now.

(I can't wait until PyPI [gets groups](https://github.com/pypa/warehouse/issues/201))

**Comment by jamadden** [comment]
Thanks. 5.3.1 has been pushed to PyPI.

**Pull request merged**
