### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by florianpilz**
Fixed more than 200 PEP8 errors and ignored folders for Virtualenv.

### CODE REVIEW

**Comment by mgedmin** [comment]
This is a bit too big to review comprehensibly.  LGTM, mostly.  Maybe let's merge the Py 2.6 support drop and rebase this so Travis is green?

Also, next time can you split the cleanups by type, e.g. blank line additions in one commit, long line wraps in another, noqa comments in a third etc. for ease of review?  (I'm not asking to split this PR because that would be too much work for too little gain, but somethig to consider for the next time.)

**Comment by florianpilz** [comment]
I like the idea of committing each set of types separately. I agree that this is very hard to review. We will wait for green testbar.

**Comment by mgedmin** [comment]
I see six merge commits on top of this!  Can you instead rebase on master?  And then do the `doctests = yes` bit in `setup.cfg` like I asked?  And then remove the now-unnecessary `# noqa` comments on imports that flake8 can see are used by doctests?  Thanks!

**Comment by florianpilz** [comment]
I added the `--doctests` option that flake8 provides via CLI and removed the two `# noqa` comments for packages used in doctests. Instead of rebasing I will just squash the commit.

**Pull request merged**
