### PR TITLE
Fix the warning "No parser was explicitly specified"

### PR DESCRIPTION
**Pull request by janjaapdriessen**

### CODE REVIEW

**Comment by mgedmin** [comment]
LGTM

**Comment by janjaapdriessen** [comment]
Can we drop 2.6 support @mgedmin? Those are failing on travis.

**Comment by janjaapdriessen** [comment]
I found in https://github.com/zopefoundation/zope.testbrowser/pull/16 that python2.6 support is dropped.

**Comment by janjaapdriessen** [comment]
I forgot to remove 2.6 from setup.py classifiers, that is already handled by Florian sitting next to me in https://github.com/zopefoundation/zope.testbrowser/pull/16

**Pull request merged**
