### PR TITLE
Allow newer WebTest versions.

### LINKED ISSUE #30: new webtest broke our tests
See https://github.com/zopefoundation/zope.testbrowser/pull/29#issuecomment-297627544

### PR DESCRIPTION
**Pull request by icemac**
2.0.28 fixed the regressions we saw with 2.0.27.
A big thank you goes to @fschulze for doing bringing up the fix there.

Fixes #30.

### CODE REVIEW

**Comment by icemac** [comment]
Could the failures have something to do with Pylons/webtest#186?

**Comment by fschulze** [comment]
This works as a fix:
```diff
diff --git a/src/zope/testbrowser/ftests/wsgitestapp.py b/src/zope/testbrowser/ftests/wsgitestapp.py
index 0de6305..a62a311 100644
--- a/src/zope/testbrowser/ftests/wsgitestapp.py
+++ b/src/zope/testbrowser/ftests/wsgitestapp.py
@@ -131,6 +131,10 @@ def set_header(req):
     resp = Response()
     body = [u"Set Headers:"]
     for k, v in sorted(req.params.items()):
+        if not isinstance(k, str):
+            k = k.encode('latin1')
+        if not isinstance(v, str):
+            v = v.encode('latin1')
         body.extend([k, v])
         resp.headers.add(k, v)
     resp.unicode_body = u'\n'.join(body)
```

I tried several iterations and it only works if it's ``str`` on both Python 2 and 3, even though ``str`` is actually unicode on Python 3. If I always encode, then it becomes ``bytes`` on Python 3 and causes another failure.

**Comment by fschulze** [comment]
This also works with the older WebTest==2.0.26

**Comment by icemac** [comment]
@fschulze Thank you for digging into this issue and finding a solution. Hopefully TravisCI gets green now.

**Pull request merged**
