### PR TITLE
Drop Python 2.6 Support

### PR DESCRIPTION
**Pull request by florianpilz**
Since beautifulsoup4 (dependency of WebTest) dropped Python 2.6 support since 4.5.0 and WebTest will drop the support in it's upcoming release, we should drop our Python 2.6 support as well.

### CODE REVIEW

**Comment by hannosch** [comment]
@florianpilz For new releases in the ZTK we no longer need to support Python 2.6. So you could also just drop 2.6 support outright.

**Comment by florianpilz** [comment]
OK, I have switched the PR. Not it is about dropping support, rather keeping it. :) The only part of code that mentions 2.6 is https://github.com/zopefoundation/zope.testbrowser/blob/master/src/zope/testbrowser/cookies.py#L58. Do you know if we can strip something out there?

**Comment by mgedmin** [comment]
LGTM.

Can you mention this drop in CHANGES.rst?

**Comment by mgedmin** [comment]
Also, yes, please drop the custom `property` subclass.

**Comment by florianpilz** [comment]
I don't feel good when removing the property hook, since the whole `cookies.py` file seems to be untested. Oo However, as far as I can tell properties have a `setter` attribute since Python 2.6 (see https://docs.python.org/2/whatsnew/2.6.html).

**Comment by florianpilz** [comment]
Since the broken 2.6 dependency blocks other PRs and this already got a 👍 I will just merge it myself.

**Pull request merged**
